[package]
name = "why3evm"
version = "0.1.0"
authors = ["Xiyue Zhang <zhangxiyue@pku.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
